# Chnage project name. We recommend you to match this name to the name of the GitHub repository
name: RecoMan
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - pip
  - requests=2.32.3
  - pandas=2.2.2
  - tqdm=4.66.5
  - pillow=10.4.0
  - fastapi 0.112.2
  - uvicorn=0.20.0
  - pytorch=2.5.1
  - torchvision
  - torchaudio
  - cpuonly
  # Place your conda dependencies here
  - pip:
    # Place your pip dependencies in requirements.txt
    - -r requirements.txt
    - -r requirements-dev.txt
