hydra:
  output_subdir: null

backend:
  host: 0.0.0.0
  port: 7777

recommender_systems:
  host: localhost
  port: 8888
  model: "matrix_factorization"
  device: "cuda:0"

dataset:
  poster_db_path: "/home/limjk/Datasets/MovieLens20M/movie_posters.sqlite"

data:
  my_rating_path: "/home/limjk/GitHub/JeiKeiLim/RecoMan/res/ratings.json"

defaults:
  - _self_
  - models/autoencoder
  - models/matrix_factorization

