backend:
  host: 0.0.0.0
  port: 7777

dataset:
  poster_db_path: "/home/limjk/Datasets/MovieLens20M/movie_posters.sqlite"

data:
  my_rating_path: "/home/limjk/GitHub/JeiKeiLim/RecoMan/res/ratings.json"
