name: format-lint-unittest

on: 
  - push
  - pull_request

jobs:
  format-lint-unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: RecoMo  # Change project name
        environment-file: environment.yml
        python-version: 3.10
        auto-activate-base: false
    - shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: [Backend] Format with black, isort
      working-directory: ./backend
      shell: bash -l {0}
      run: ./run_check.sh format
    - name: [Backend] Lint with pylint, mypy, flake8
      working-directory: ./backend
      shell: bash -l {0}
      run: ./run_check.sh lint
    - name: [Recommendation] Format with black, isort
      working-directory: ./recommender_systems
      shell: bash -l {0}
      run: ./run_check.sh format
    - name: [Recommendation] Lint with pylint, mypy, flake8
      working-directory: ./recommender_systems
      shell: bash -l {0}
      run: ./run_check.sh lint
    # - name: Test with pytest
    #   shell: bash -l {0}
    #   run: ./run_check.sh test
